### PR TITLE
Connect frameworks

### PR DESCRIPTION
**Pull request by pinpimarn**
- Connect two framwork together
- Add POST, PATCH, GET request
- Edit LINE redirect on setting page
- Rearrange page components and decorations

### CODE REVIEW

**Comment by dzptahh** [comment]
well done

**Comment by crparichaya** [comment]
look good

**Comment by JiratchayaPhinyodom** [comment]
+1

**Comment by JiratchayaPhinyodom** [comment]
Mage got in the wrong place.

**Pull request merged**
