### PR TITLE
Connect Frameworks new

### PR DESCRIPTION
**Pull request by pinpimarn**
- Connect two framwork together
- Add POST, PATCH, GET request
- Edit LINE redirect on setting page
- Rearrange page components and decorations

### CODE REVIEW

**Comment by JiratchayaPhinyodom** [comment]
If you have already fixed conflicts. You can come to Merge.

**Comment by JiratchayaPhinyodom** [comment]
Well done.

**Comment by crparichaya** [comment]
look good

**Comment by dzptahh** [comment]
great

**Comment by JiratchayaPhinyodom** [comment]
If you have already fixed conflicts. You can come to Merge.

**Pull request merged**
